server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # Ya que es un servidor no debe registrarse a sí mismo.
    fetch-registry: false        # No debería buscar en su propio registro.
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: FOOD-CATALOGUE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/foodcataloguedb?createDatabaseIfNotExist=true
    username: root
    password: 2628
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
